[set.elementalhero]
code = 12296
[set.maskedhero]
code = 40968
[set.change]
code = 165
[set.favorite]
code = 405
[set.kuriboh]
code = 164

[[card]]
id = 100010001
name = "Favorite: Change Polymerization"
type = "quickplay spell"
set = "favorite change"
effect = '''Fusion Summon 1 "Hero" monster using materials from your Extra Deck.
You can banish this card from your GY: Add one "Mask Change" or "Polymerization" from your GY to your hand.
You can only use each effect of "Favorite: Change Polymerization" once per turn.'''

[[card]]
id = 100010002
name = "Favorite: Winged Kuriboh - Level 1"
type = "effect monster"
race = "fairy"
attribute = "light"
level = 1
atk = 300
def = 200
set = "elementalhero favorite kuriboh"
effect = '''(This card is always treated as an "Elemental Hero" card.)
You can Special Summon this card (from your hand) by sending a "Polymerization" or "Change" card from your Deck to the GY.
You can tribute a "Hero" monster you control: Add one "Favorite" card from your Deck to your hand.
You can banish a "Polymerization" or "Change" card from your GY: Add this card from your GY to your hand.
You can only use each effect of "Favorite: Winged Kuriboh - Level 1" once per turn.'''

[[card]]
id = 100010003
name = "Favorite: Winged Kuriboh - Level 8"
type = "effect monster"
race = "fairy"
attribute = "light"
level = 8
atk = 300
def = 200
set = "elementalhero favorite kuriboh"
effect = '''(This card is always treated as an "Elemental Hero" card.)
You can Special Summon this card (from your hand) by banishing one "Kuriboh" monster from your GY.
If this card is Special Summoned: you can tribute this card: Special Summon one level 7 or lower "Hero" monster from your Deck.
You can banish this card from your GY in response to your opponent's monster effect: negate that effect.'
You can only use each effect of "Favorite: Winged Kuriboh - Level 8" once per duel.'''

[[card]]
id = 100010004
name = "Masked Hero Goka - Transformation"
type = "effect monster"
race = "warrior"
attribute = "fire"
level = 6
atk = 2200
def = 1800
set = "maskedhero"
effect = '''You can Special Summon this card (from your hand) by banishing one "Masked Hero" from your Deck.
If a card is added to your hand (except during the Draw Phase or the Damage Step): You can add a Level 5 or higher "Hero" monster from your Deck to your hand.
You can only use these effects of "Masked Hero Goka - Transformation" once per turn.
If this card is Normal Summoned: You can Special Summon one of your level 4 or lower "Hero" monsters that is in your GY or banished.
Once per turn: You can shuffle one "Fusion", "Change", or Level 5 or higher "Hero" card from your hand to your Deck, then add one level 4 or lower "Hero" monster from your Deck to your hand.'''

[[card]]
id = 100010005
name = "Masked Hero Vapor - Transformation"
type = "effect monster"
race = "warrior"
attribute = "water"
level = 6
atk = 2400
def = 2000
set = "maskedhero"
effect = '''You can reveal this card in your hand: immediately after this effect resolves, Normal Summon a "Hero" monster from your hand.
If this card is Normal or Special Summoned: you can add one "Fusion" or "Change" card that is in your GY or banished to your hand.
You can only use these effects of "Masked Hero Vapor - Transformation" once per turn.
If this card is sent to the GY: Send one "Elemental Hero", "Masked Hero", "Change", or "Fusion" card from your Deck to the GY.'''

[[card]]
id = 100010006
name = "Masked Hero Divine Wind - Change!!!"
type = "effect monster"
race = "warrior"
attribute = "wind"
level = 8
atk = 2700
def = 1900
set = "maskedhero"
effect = '''You can Special Summon this card (from your hand) by tributing another "Hero" monster from your hand or field.
You can only use this effect of "Masked Hero Divine Wind - Change!!!" once per turn.
Once per turn, you can tribute a "Hero" monster you control: Special Summon a level 4 or lower "Elemental Hero" or "Masked Hero" from your Deck. You can only Special Summon "Elemental Hero" and "Masked Hero" monsters for the rest of the turn after you activate this effect.'''

[[card]]
id = 100010007
name = "Masked Hero Koga - Change!!!"
type = "effect monster"
race = "warrior"
attribute = "light"
level = 8
atk = 2700
def = 1800
set = "maskedhero"
effect = '''You can Special Summon this card (from your hand) by tributing another "Hero" monster from your hand or field.
You can only use this effect of "Masked Hero Koga - Change!!!" once per turn.
Once per turn, you can set a "Fusion" or "Change" Spell/Trap card from your Deck, then add one level 7 or lower "Hero" monster from your Deck to your hand. You can only Special Summon "Elemental Hero" and "Masked Hero" monsters for the rest of the turn after you activate this effect.'''


[[card]]
id = 100010008
name = "Masked Hero Dian - Change!!!"
type = "effect monster"
race = "warrior"
attribute = "earth"
level = 8
atk = 2800
def = 3000
set = "maskedhero"
effect = '''Once per turn, you can Special Summon a level 7 or lower "Hero" monster from your hand.
You can only use the following effects of "Masked Hero Dian - Change!!!" once per turn.
You can Special Summon this card (from your hand) by tributing another "Hero" monster from your hand or field.
If this card is sent to the GY: Add a "Fusion" or "Change" card from your Deck to the hand. You can only Special Summon "Elemental Hero" and "Masked Hero" monsters for the rest of the turn after you use this effect.'''

[[card]]
id = 100010009
name = "Masked Hero Anki - Change!!!"
type = "effect monster"
race = "warrior"
attribute = "dark"
level = 8
atk = 2800
def = 1200
set = "maskedhero"
effect = '''Once per turn, you can send a "Hero" monster from your Extra Deck to the GY, then send a "Mask Change" from your Deck to the GY: Apply that card's effect.
You can only use the following effects of "Masked Hero Anki - Change!!!" once per turn.
You can Special Summon this card (from your hand) by tributing another "Hero" monster from your hand or field.
You can banish this card from your GY: Add one "Hero", "Fusion", or "Change" card from your GY to your hand. You can only Special Summon "Elemental Hero" and "Masked Hero" monsters for the rest of the turn after you activate this effect.'''